// AUTO-GENERATED by scripts/build-bible-data.ts — do not edit by hand.
// Canonical 66-book table joining the Dutch Statenvertaling's book names
// with the KJV's, by canonical position (both list Genesis..Revelation in
// the same order). Committed as source (unlike data/bible/*, which is
// gitignored) because client/src/lib/sermon/bible-ref.ts needs only this
// small table, never verse text — see CLAUDE.md "Scripture pipeline".

export interface BibleBook {
  n: number;
  nl: string;
  en: string;
  /** Dutch short form from the Statenvertaling source (e.g. "Joh", "1Kor") — a starting point, not an exhaustive alias set. */
  abbr: string;
}

export const BIBLE_BOOKS: BibleBook[] = [
  {
    "n": 1,
    "nl": "Genesis",
    "en": "Genesis",
    "abbr": "Gen"
  },
  {
    "n": 2,
    "nl": "Exodus",
    "en": "Exodus",
    "abbr": "Ex"
  },
  {
    "n": 3,
    "nl": "Leviticus",
    "en": "Leviticus",
    "abbr": "Lev"
  },
  {
    "n": 4,
    "nl": "Numeri",
    "en": "Numbers",
    "abbr": "Numeri"
  },
  {
    "n": 5,
    "nl": "Deuteronomium",
    "en": "Deuteronomy",
    "abbr": "Deut"
  },
  {
    "n": 6,
    "nl": "Jozua",
    "en": "Joshua",
    "abbr": "Joz"
  },
  {
    "n": 7,
    "nl": "Richteren",
    "en": "Judges",
    "abbr": "Ri"
  },
  {
    "n": 8,
    "nl": "Ruth",
    "en": "Ruth",
    "abbr": "Ruth"
  },
  {
    "n": 9,
    "nl": "1 Samuel",
    "en": "1 Samuel",
    "abbr": "1Sam"
  },
  {
    "n": 10,
    "nl": "2 Samuel",
    "en": "2 Samuel",
    "abbr": "2Sam"
  },
  {
    "n": 11,
    "nl": "1 Koningen",
    "en": "1 Kings",
    "abbr": "1Kon"
  },
  {
    "n": 12,
    "nl": "2 Koningen",
    "en": "2 Kings",
    "abbr": "2Kon"
  },
  {
    "n": 13,
    "nl": "1 Kronieken",
    "en": "1 Chronicles",
    "abbr": "1Kron"
  },
  {
    "n": 14,
    "nl": "2 Kronieken",
    "en": "2 Chronicles",
    "abbr": "2Kron"
  },
  {
    "n": 15,
    "nl": "Ezra",
    "en": "Ezra",
    "abbr": "Ezra"
  },
  {
    "n": 16,
    "nl": "Nehemia",
    "en": "Nehemiah",
    "abbr": "Neh"
  },
  {
    "n": 17,
    "nl": "Ester",
    "en": "Esther",
    "abbr": "Est"
  },
  {
    "n": 18,
    "nl": "Job",
    "en": "Job",
    "abbr": "Job"
  },
  {
    "n": 19,
    "nl": "Psalmen",
    "en": "Psalms",
    "abbr": "Ps"
  },
  {
    "n": 20,
    "nl": "Spreuken",
    "en": "Proverbs",
    "abbr": "Spr"
  },
  {
    "n": 21,
    "nl": "Prediker",
    "en": "Ecclesiastes",
    "abbr": "Pred"
  },
  {
    "n": 22,
    "nl": "Hooglied",
    "en": "Song of Solomon",
    "abbr": "Hoogl"
  },
  {
    "n": 23,
    "nl": "Jesaja",
    "en": "Isaiah",
    "abbr": "Jes"
  },
  {
    "n": 24,
    "nl": "Jeremia",
    "en": "Jeremiah",
    "abbr": "Jer"
  },
  {
    "n": 25,
    "nl": "Klaagliederen",
    "en": "Lamentations",
    "abbr": "Kla"
  },
  {
    "n": 26,
    "nl": "Ezechiel",
    "en": "Ezekiel",
    "abbr": "Ezech"
  },
  {
    "n": 27,
    "nl": "Daniel",
    "en": "Daniel",
    "abbr": "Dan"
  },
  {
    "n": 28,
    "nl": "Hosea",
    "en": "Hosea",
    "abbr": "Hos"
  },
  {
    "n": 29,
    "nl": "Joel",
    "en": "Joel",
    "abbr": "Joel"
  },
  {
    "n": 30,
    "nl": "Amos",
    "en": "Amos",
    "abbr": "Am"
  },
  {
    "n": 31,
    "nl": "Obadja",
    "en": "Obadiah",
    "abbr": "Ob"
  },
  {
    "n": 32,
    "nl": "Jona",
    "en": "Jonah",
    "abbr": "Jona"
  },
  {
    "n": 33,
    "nl": "Micha",
    "en": "Micah",
    "abbr": "Mi"
  },
  {
    "n": 34,
    "nl": "Nahum",
    "en": "Nahum",
    "abbr": "Nah"
  },
  {
    "n": 35,
    "nl": "Habakuk",
    "en": "Habakkuk",
    "abbr": "Hab"
  },
  {
    "n": 36,
    "nl": "Zefanja",
    "en": "Zephaniah",
    "abbr": "Zef"
  },
  {
    "n": 37,
    "nl": "Haggai",
    "en": "Haggai",
    "abbr": "Hag"
  },
  {
    "n": 38,
    "nl": "Zacharia",
    "en": "Zechariah",
    "abbr": "Zach"
  },
  {
    "n": 39,
    "nl": "Maleachi",
    "en": "Malachi",
    "abbr": "Mal"
  },
  {
    "n": 40,
    "nl": "Matteus",
    "en": "Matthew",
    "abbr": "Mat"
  },
  {
    "n": 41,
    "nl": "Marcus",
    "en": "Mark",
    "abbr": "Mar"
  },
  {
    "n": 42,
    "nl": "Lucas",
    "en": "Luke",
    "abbr": "Luc"
  },
  {
    "n": 43,
    "nl": "Johannes",
    "en": "John",
    "abbr": "Joh"
  },
  {
    "n": 44,
    "nl": "Handelingen der apostelen",
    "en": "Acts",
    "abbr": "Hand"
  },
  {
    "n": 45,
    "nl": "Romeinen",
    "en": "Romans",
    "abbr": "Rom"
  },
  {
    "n": 46,
    "nl": "1 Korinthiers",
    "en": "1 Corinthians",
    "abbr": "1Kor"
  },
  {
    "n": 47,
    "nl": "2 Korintiers",
    "en": "2 Corinthians",
    "abbr": "2Kor"
  },
  {
    "n": 48,
    "nl": "Galaten",
    "en": "Galatians",
    "abbr": "Gal"
  },
  {
    "n": 49,
    "nl": "Efeziers",
    "en": "Ephesians",
    "abbr": "Ef"
  },
  {
    "n": 50,
    "nl": "Filippenzen",
    "en": "Philippians",
    "abbr": "Fil"
  },
  {
    "n": 51,
    "nl": "Kolossenzen",
    "en": "Colossians",
    "abbr": "Kol"
  },
  {
    "n": 52,
    "nl": "1 Tessalonicenzen",
    "en": "1 Thessalonians",
    "abbr": "1Tes"
  },
  {
    "n": 53,
    "nl": "2 Tessalonicenzen",
    "en": "2 Thessalonians",
    "abbr": "2Tes"
  },
  {
    "n": 54,
    "nl": "1 Timoteus",
    "en": "1 Timothy",
    "abbr": "1Tim"
  },
  {
    "n": 55,
    "nl": "2 Timoteus",
    "en": "2 Timothy",
    "abbr": "2Tim"
  },
  {
    "n": 56,
    "nl": "Titus",
    "en": "Titus",
    "abbr": "Tit"
  },
  {
    "n": 57,
    "nl": "Filemon",
    "en": "Philemon",
    "abbr": "Filem"
  },
  {
    "n": 58,
    "nl": "Hebreeen",
    "en": "Hebrews",
    "abbr": "Hebr"
  },
  {
    "n": 59,
    "nl": "Jakobus",
    "en": "James",
    "abbr": "Jak"
  },
  {
    "n": 60,
    "nl": "1 Petrus",
    "en": "1 Peter",
    "abbr": "1Petr"
  },
  {
    "n": 61,
    "nl": "2 Petrus",
    "en": "2 Peter",
    "abbr": "2Petr"
  },
  {
    "n": 62,
    "nl": "1 Johannes",
    "en": "1 John",
    "abbr": "1Joh"
  },
  {
    "n": 63,
    "nl": "2 Johannes",
    "en": "2 John",
    "abbr": "2Joh"
  },
  {
    "n": 64,
    "nl": "3 Johannes",
    "en": "3 John",
    "abbr": "3Joh"
  },
  {
    "n": 65,
    "nl": "Judas",
    "en": "Jude",
    "abbr": "Jud"
  },
  {
    "n": 66,
    "nl": "Openbaring van Johannes",
    "en": "Revelation",
    "abbr": "Openb"
  }
];
